config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords]
  get "dashboard", to: "dashboards#index"

  # authenticated :user do
  #   root "dashboards#show", as: :authenticated_root
  # end
  #
  # unauthenticated do
  #   root "home#index" # Or whatever your public landing page is
  # end

  root "home#index"
  get 'retailer_list', to: 'home#retailer_list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  post "/checkouts", to: "checkouts#create"
  post '/webhooks/stripe', to: 'webhooks#stripe'
  get 'post_checkout', to: 'checkouts#success'
  get 'billing_portal/:id', to: 'dashboards#billing_portal', as: :billing_portal
  get '/users/sign_up', to: redirect('/users/sign_in')

  get '/magic_login/:token', to: 'magic_links#show', as: :magic_login
  post '/send_magic_link', to: 'magic_links#create', as: :send_magic_link
  namespace :api do
    namespace :v1 do
      post 'qogita_product_info', to: 'qogita#product_info'
      post 'amazon_product_info', to: 'amazon#product_info'
    end
  end
end

app/views/shared/_dashboard_header.hmtl.erb
<header class="site-header site-header--menu-left site-header--absolute">
  <div class="container">
    <nav class="navbar site-navbar offcanvas-active navbar-expand-lg  px-0">
      <!-- Brand Logo-->
      <div class="brand-logo"><a href="https://oahero.com">
        <!-- light version logo (logo must be black)-->
        <%#= image_tag "image/OAHero-logo-light.png", alt: "Logo" %>
        <!-- Dark version logo (logo must be White)-->
        <%= image_tag "image/OAHero-logo-dark.png", class: "dark-version-logo" %>
      </a>
      </div>

      <div class="collapse navbar-collapse" id="mobile-menu">
        <div class="navbar-nav-wrapper">
          <ul class="navbar-nav main-menu pt-8">
            <li class="nav-item">
              <a class="nav-link" href="https://www.oahero.com/" role="button" aria-expanded="false">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://g.fbamogul.com/support-server" role="button" aria-expanded="false", target="_blank">Support</a>
            </li>
            <li class="nav-item">
              <%= link_to "Site List", retailer_list_path, class: "nav-link", role: "button", "aria-expanded": "false" %>
            </li>
            <%= link_to 'Download', ENV["OA_HERO_DOWNLOAD_URL"], target: "_blank",
                        class: "btn btn-sm btn-outline-light rounded-8 gr-hover-y mr-3" %>
          </ul>
        </div>

        <div class="ml-auto d-flex align-items-center pt-8">
          <% if user_signed_in? %>

            <%= link_to 'Dashboard', dashboard_path,
                        class: "btn btn-sm btn-outline-light rounded-8 gr-hover-y mr-3" %>

            <%= button_to 'Logout', destroy_user_session_path,
                          method: :delete,
                          class: "btn btn-sm btn-red rounded-8 gr-hover-y" %>
          <% else %>
            <%= link_to 'Login', new_user_session_path,
                        class: "btn btn-sm btn-primary rounded-8 gr-hover-y" %>
          <% end %>
        </div>
    </nav>
  </div>
</header>

app/views/shared/_dashboard_header.html.erb
<header class="site-header site-header--menu-left site-header--absolute">
  <div class="container">
    <nav class="navbar site-navbar offcanvas-active navbar-expand-lg  px-0">
      <!-- Brand Logo-->
      <div class="brand-logo"><a href="https://oahero.com">
        <!-- light version logo (logo must be black)-->
        <%#= image_tag "image/OAHero-logo-light.png", alt: "Logo" %>
        <!-- Dark version logo (logo must be White)-->
        <%= image_tag "image/OAHero-logo-dark.png", class: "dark-version-logo" %>
      </a>
      </div>

      <div class="collapse navbar-collapse" id="mobile-menu">
        <div class="navbar-nav-wrapper">
          <ul class="navbar-nav main-menu pt-8">
            <li class="nav-item">
              <a class="nav-link" href="https://www.oahero.com/" role="button" aria-expanded="false">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://g.fbamogul.com/support-server" role="button" aria-expanded="false", target="_blank">Support</a>
            </li>
            <li class="nav-item">
              <%= link_to "Site List", retailer_list_path, class: "nav-link", role: "button", "aria-expanded": "false" %>
            </li>
          </ul>
        </div>

        <div class="ml-auto d-flex align-items-center pt-8">
          <% if user_signed_in? %>

            <%= link_to 'Download', ENV["OA_HERO_DOWNLOAD_URL"],
                        class: "btn btn-sm btn-blue rounded-8 gr-hover-y mr-3" %>

            <%= button_to 'Logout', destroy_user_session_path,
                          method: :delete,
                          class: "btn btn-sm btn-red rounded-8 gr-hover-y" %>
          <% else %>
            <%= link_to 'Login', new_user_session_path,
                        class: "btn btn-sm btn-primary rounded-8 gr-hover-y" %>
          <% end %>
        </div>
    </nav>
  </div>
</header>

app/views/shared/_footer.html.erb
<div class="footer-section pt-15 pt-lg-25 pb-lg-21 dark-mode-texts bg-blackish-blue border-top border-gray-3">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-3 col-md-4">
        <div class="footer-logo mb-11">
          <%= image_tag "image/OAHero-logo-footer.png" %>
        </div>
        <p class="gr-text-11">Your ultimate sourcing companion!</p>
        <ul class="social-icons py-7 list-unstyled mb-7 mb-lg-0">
          <li class="mr-2"><a href="" class="text-storm gr-hover-text-green"><i class="icon icon-logo-twitter"></i></a></li>
          <li class="mr-2"><a href="" class="text-storm gr-hover-text-green"><i class="icon icon-logo-facebook"></i></a></li>
          <li class="mr-2"><a href="" class="text-storm gr-hover-text-green"><i class="icon icon-instant-camera-2"></i></a></li>
          <li class="mr-2"><a href="" class="text-storm gr-hover-text-green"><i class="icon icon-logo-linkedin"></i></a></li>
        </ul>
      </div>
      <!--        <div class="col-lg-8 offset-lg-1 col-md-8">-->
      <!--          <div class="row">-->
      <!--            <div class="col-xs-6 col-lg-3">-->
      <!--              <div class="single-footer mb-13 mb-lg-9">-->
      <!--                <p class="footer-title gr-text-11 mb-7">Company</p>-->
      <!--                <ul class="footer-list list-unstyled gr-text-9">-->
      <!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">About us</a></li>-->
      <!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">Contact us</a></li>-->
      <!--                </ul>-->
      <!--              </div>-->
      <!--            </div>-->
      <!--            <div class="col-xs-6 col-lg-3">-->
      <!--              <div class="single-footer mb-13 mb-lg-9">-->
      <!--                <p class="footer-title gr-text-11 mb-7">Product</p>-->
      <!--                <ul class="footer-list list-unstyled gr-text-9">-->
      <!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">FAQ</a></li>-->
      <!--                  <li class="py-2"><a href="https://discord.gg/jcxYbBKaku" class="gr-text-color gr-hover-text-green">Support</a></li>-->
      <!--                </ul>-->
      <!--              </div>-->
      <!--            </div>-->
      <!--            <div class="col-xs-6 col-lg-3">-->
      <!--              <div class="single-footer mb-13 mb-lg-9">-->
      <!--                <p class="footer-title gr-text-11 mb-7">Legal</p>-->
      <!--                <ul class="footer-list list-unstyled gr-text-9">-->
      <!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">Privacy Policy</a></li>-->
      <!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">Terms &amp; Conditions</a></li>-->
      <!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">Return Policy</a></li>-->
      <!--                </ul>-->
      <!--              </div>-->
      <!--            </div>-->
      <!--          </div>-->
      <!--        </div>-->
      <!--<!--<div class="col-lg-8 offset-lg-1 col-md-8">-->
      <!--<!--          <div class="row">-->
      <!--<!--            <div class="col-xs-6 col-lg-3">-->
      <!--<!--              <div class="single-footer mb-13 mb-lg-9">-->
      <!--<!--                <p class="footer-title gr-text-11 mb-7">Company</p>-->
      <!--<!--                <ul class="footer-list list-unstyled gr-text-9">-->
      <!--<!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">About us</a></li>-->
      <!--<!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">Contact us</a></li>-->
      <!--<!--                </ul>-->
      <!--<!--              </div>-->
      <!--<!--            </div>-->
      <!--<!--            <div class="col-xs-6 col-lg-3">-->
      <!--<!--              <div class="single-footer mb-13 mb-lg-9">-->
      <!--<!--                <p class="footer-title gr-text-11 mb-7">Product</p>-->
      <!--<!--                <ul class="footer-list list-unstyled gr-text-9">-->
      <!--<!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">FAQ</a></li>-->
      <!--<!--                  <li class="py-2"><a href="https://discord.gg/jcxYbBKaku" class="gr-text-color gr-hover-text-green">Support</a></li>-->
      <!--<!--                </ul>-->
      <!--<!--              </div>-->
      <!--<!--            </div>-->
      <!--<!--            <div class="col-xs-6 col-lg-3">-->
      <!--<!--              <div class="single-footer mb-13 mb-lg-9">-->
      <!--<!--                <p class="footer-title gr-text-11 mb-7">Legal</p>-->
      <!--<!--                <ul class="footer-list list-unstyled gr-text-9">-->
      <!--<!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">Privacy Policy</a></li>-->
      <!--<!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">Terms &amp; Conditions</a></li>-->
      <!--<!--                  <li class="py-2"><a href="" class="gr-text-color gr-hover-text-green">Return Policy</a></li>-->
      <!--<!--                </ul>-->
      <!--<!--              </div>-->
      <!--<!--            </div>-->
      <!--<!--          </div>-->
      <!--<!--        </div>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_header.html.erb
<header class="site-header site-header--menu-left site-header--absolute">
  <div class="container">
    <nav class="navbar site-navbar offcanvas-active navbar-expand-lg  px-0">
      <!-- Brand Logo-->
      <div class="brand-logo"><a href="https://oahero.com">
        <!-- light version logo (logo must be black)-->
        <%#= image_tag "image/OAHero-logo-light.png", alt: "Logo" %>
        <!-- Dark version logo (logo must be White)-->
        <%= image_tag "image/OAHero-logo-dark.png", class: "dark-version-logo" %>
      </a>
      </div>

      <div class="collapse navbar-collapse" id="mobile-menu">
        <div class="navbar-nav-wrapper">
          <ul class="navbar-nav main-menu pt-8">
            <li class="nav-item">
              <a class="nav-link" href="https://www.oahero.com/" role="button" aria-expanded="false">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#features" role="button" aria-expanded="false">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#pricing" role="button" aria-expanded="false">Pricing</a>
            </li>
            <!--              <li class="nav-item">-->
            <!--                <a class="nav-link" href="https://uxtheme.net/product-support/" role="button" aria-expanded="false">FAQ</a>-->
            <!--              </li>-->
            <li class="nav-item">
              <a class="nav-link" href="https://g.fbamogul.com/support-server" role="button" aria-expanded="false", target="_blank">Support</a>
            </li>
          </ul>
        </div>

        <div class="ml-auto d-flex align-items-center pt-8">
          <% if user_signed_in? %>

            <%= link_to 'Dashboard', dashboard_path,
                        class: "btn btn-sm btn-outline-light rounded-8 gr-hover-y mr-3" %>

            <%= button_to 'Logout', destroy_user_session_path,
                          method: :delete,
                          class: "btn btn-sm btn-red rounded-8 gr-hover-y" %>
          <% else %>
            <%= link_to 'Login', new_user_session_path,
                        class: "btn btn-sm btn-primary rounded-8 gr-hover-y" %>
          <% end %>
        </div>
    </nav>
  </div>
</header>